services:
  squirrel.api:
    image: squirrel.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Squirrel.Api/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      squirrel.db:
        condition: service_healthy
    networks:
      - nginx-network
  
  squirrel.db:
    image: postgres:latest
    container_name: squirrel.db
    environment:
      - POSTGRES_DB=squirrel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - nginx-network
    
  squirrel.seq:
    image: datalust/seq:latest
    container_name: squirrel.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8080:80
    networks:
      - nginx-network
  
  squirrel.redis:
    image: redis:latest
    container_name: squirrel.redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - nginx-network
        
  ngnix:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - squirrel.api
    networks:
      - nginx-network
        
networks:
  nginx-network:
    driver: bridge
  