services:
  squirrel.api:
    image: squirrel.api
    build:
      context: .
      dockerfile: src/Squirrel.Api/Dockerfile
    ports:
      - 8081:8080
  
  squirrel-db:
    image: postgres:latest
    container_name: squirrel.db
    environment:
      - POSTGRES_DB=squirrel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/Data
    ports:
      - 5432:5432
  